### PR TITLE
Address issue #41 - deployed .csproj files have ASPNETCORE_ENVIRONMENT=Development

### PR DESCRIPTION
**Pull request by skotl**
## Proposed change

Rename `launchSettings.json` and add it to `.gitignore`

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [x] Breaking change (fix/feature - note the _potential_ break is in dev mode, not in production

## Additional information
 * This PR fixes or closes issue: fixes # 41
 * This PR is related to issue:
 * Link to documentation pull request:

This is intended to address [Issue 41](https://github.com/net-daemon/netdaemon-app-template/issues/41) which was originally reported as .csproj solutions honouring the `[Focus]` attribute, which turned out to be due to `ASPNETCORE_ENVIRONMENT=Development` leaking into the environment.

Please see the issue for more details on the investigation and suggested mitigation. This PR seems like the least painful option, in that I've renamed `launchSettings.json` to `_launchSettings.json` and added the original to `.gitignore`.
This allows anyone with downstream forks to rename the file back again on their local PC, and it won't be pushed to the repo or deployed to the HomeAssistant production environment.

I've updated `README.md` to suggest renaming the file.

## Testing

This issue should only apply to .csproj configurations. Tested on a "Home Assistant OS" deployment and verified before and after behaviour is as expected.

## Checklist
 - [x] The code change is tested and works locally.
 - [x] Local tests pass. Your PR cannot be merged unless tests pass
 - [x] There is no commented out code in this PR.
 - [x] I have followed the [development checklist][dev-checklist]
 - [x] The code compiles without warnings (code quality chek)
 - [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

 - [x] Documentation added/updated for: README.md

### CODE REVIEW

**Comment by FrankBakkerNl** [comment]
Wouldn't the launchesettings file now still be copied when you deploy the project?

It is unfortunate that this now requires an extra step for the dev environment which might be forgotten, while deploying .csoroj is not the most common deployment strategy. 

What do you think @helto4real !

**Comment by skotl** [comment]
Ah – it depends on your deployment workflow: I’m doing a git pull on the HASS machine so this works in that scenario, but if you were copying the files over then yes it would still end up there :(

**Comment by skotl** [comment]
A little more detail on impact:

1. For new forkers, the instructions now say to copy launchSettings, so I think they're covered
2. For existing maintainers who pull or fetch there will be a _one-time_ requirement to rename or copy their `_launchSettings.json` (but only if they need or want the Development setting)
3. For people who don't deploy via `.csproj` there are is more impact - previous behaviour will be maintained
4. For people who do deploy via `.csproj`:
    * Those who use `git pull` to update prod will see the desired effect, that `launchSettings.json` is not propagated
    * Those who use a bulk copy solution will see the current behaviour, but _should_ delete `launchSettings.json` as part of the script
 
Hope that helps.
Cheers

**Comment by skotl** [comment]
As discussed, closing this in lieu of additional documentation (PR #90 on `netdaemon-docs`)

**Pull request closed without merging**
